---
- name: Set up the bastion host as an ansible controller host
  hosts: bastion
  become: True

  tasks:
    - name: Install EPEL repository on RedHat
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
      when: ansible_distribution == 'RedHat'
    - name: Install EPEL repository on CentOS
      yum:
        name: epel-release
        state: present
      remote_user: centos
      when: ansible_distribution == 'CentOS'
#    - name: Update packages
#      yum:
#        name: '*'
#        state: latest
    - name: Install ansible and docker
      yum:
        name: ansible, docker
        state: present
    - name: Enable and start docker service
      service:
        name: docker
        state: started
        enabled: True
...
