---
- name: Update local inventory file
  hosts: local

  tasks:
    - name: Create variables file from terraform output EC2 outputs
      shell: terraform output |tr '=' ':' > ../../ansible/terraform_outputs.var
      args:
        chdir: ../terraform/EC2/
    - name: Add variables to file from terraform S3 outputs
      shell: terraform output |tr '=' ':' >> ../../ansible/terraform_outputs.var
      args:
        chdir: ../terraform/S3/
    - name: Load the terraform output variables
      include_vars:
        file: terraform_outputs.var
    - name: Apply inventory template
      template:
        src: templates/inventario.j2
        dest: inventario
    - name: Apply ssh config template
      template:
        src: templates/ssh_cfg.j2
        dest: ../ssh.cfg
    - name: Reload inventory file
      meta: refresh_inventory

- name: Dummy connection to bastion host
  hosts: bastion

  tasks:
    - name: Just a simple message
      debug:
        msg: Hello from bastion

- name: Setup docker and docker compose
  hosts: aws
  become: True

  tasks:
    - name: Install EPEL repository on RedHat
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
      when: ansible_distribution == 'RedHat'
    - name: Install EPEL repository on CentOS
      yum:
        name: epel-release
        state: present
      remote_user: centos
      when: ansible_distribution == 'CentOS'
    - name: Install docker and docker compose
      yum:
        name: docker, docker-compose
        state: present
    - name: Enable and start docker service
      service:
        name: docker
        state: started
        enabled: True

- name: Set up harbor
  hosts: registry
  become: True
  vars_files:
    - terraform_outputs.var

  tasks:
    - name: Download harbor online installer
      get_url:
        url: https://storage.googleapis.com/harbor-releases/release-1.6.0/harbor-online-installer-v1.6.0.tgz
        dest: /tmp/
    - name: Unpack harbor installer
      unarchive:
        src: /tmp/harbor-online-installer-v1.6.0.tgz
        dest: /opt
        remote_src: True
    - name: Add harbor config file from template
      template:
        src: templates/harbor.j2
        dest:  /opt/harbor/harbor.cfg
    - name: Apply Storage backend template
      template:
       src: templates/config.j2
       dest: /opt/harbor/common/templates/registry/config.yml
    - name: Run installation script
      command: ./install.sh
      args:
        chdir: /opt/harbor
        creates: /data/database/postmaster.pid
...
