---
- name: Update local inventory file
  hosts: local

  tasks:
    - name: Create variables file from terraform output EC2 outputs
      shell: terraform output |tr '=' ':' > ../../ansible/terraform_outputs.var
      args:
        chdir: ../terraform/EC2/
    - name: Add variables from terraform S3 outputs
      shell: terraform output |tr '=' ':' >> ../../ansible/terraform_outputs.var
      args:
        chdir: ../terraform/S3/
    - name: Load the terraform output variables
      include_vars:
        file: terraform_outputs.var
    - name: Apply inventory template
      template:
        src: templates/inventario.j2
        dest: inventario
    - name: Apply ssh config template
      template:
        src: templates/ssh_cfg.j2
        dest: ../ssh.cfg
    - name: Reload inventory file
      meta: refresh_inventory

- name: Dummy connection to bastion host
  hosts: bastion

  tasks:
    - name: Just a simple message
      debug:
        msg: Hello from bastion

- name: Setup docker and docker compose
  hosts: aws
  become: True
  vars_files:
    - terraform_outputs.var

  tasks:
    - name: Install EPEL repository on RedHat
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
      when: ansible_distribution == 'RedHat'
    - name: Install EPEL repository on CentOS
      yum:
        name: epel-release
        state: present
      remote_user: centos
      when: ansible_distribution == 'CentOS'
    - name: Install docker and docker compose
      yum:
        name: docker, docker-compose
        state: present
    - name: Enable and start docker service
      service:
        name: docker
        state: started
        enabled: True
    - name: Add registry certificate to docker
      block:
          - name: Create directory for registry certs
            file:
              path: /etc/docker/certs.d/{{ registry_IP }}
              state: directory
          - name: Copy CA public cert from registry to docker client certificates
            copy:
              src: files/CA.pem
              dest: /etc/docker/certs.d/{{ registry_IP }}/ca.crt
      when: inventory_hostname == bastion_name

- name: Set up harbor
  hosts: registry
  become: True
  vars_files:
    - terraform_outputs.var

  tasks:
    - name: Stat local installer package
      stat:
        path: /tmp/{{ installer_package }}
      register: installer
    - name: Download harbor installer package
      get_url:
        url: https://storage.googleapis.com/harbor-releases/{{ installer_package }}
        dest: /tmp/
      when: not installer.stat.exists
    - name: Unpack harbor installer
      unarchive:
        src: /tmp/{{ installer_package }}
        dest: /opt
        remote_src: True
    - name: Make directory to hold certificates
      file:
        path: /registry_certs
        state: directory
        mode: 0400
    - name: Copy certificate file
      copy:
        src: files/registry.tanami.xyz.crt
        dest: /registry_certs
    - name: Copy key file
      copy:
        src: files/registry.tanami.xyz.key
        dest: /registry_certs
        mode: 0600
    - name: Add harbor config file from template
      template:
        src: templates/harbor.j2
        dest: "{{ harbor_path }}/harbor.cfg"
    - name: Apply Storage backend template
      template:
       src: templates/config.j2
       dest: "{{ harbor_path }}/common/templates/registry/config.yml"
    - name: Run installation script
      command: ./install.sh
      args:
        chdir: "{{ harbor_path }}"
        creates: /data/database/postmaster.pid
...
