---
- name: Update local inventory file
  hosts: local

  tasks:
    - name: Create variables file from terraform output
      shell: terraform output |tr '=' ':' > ../../ansible/terraform_outputs.var
      args:
        chdir: ../terraform/VPC/
    - name: Load the terraform out variables
      include_vars:
        file: terraform_outputs.var
    - name: Apply inventory template
      template:
        src: templates/inventario.j2
        dest: inventario
    - name: Apply ssh config template
      template:
        src: templates//ssh_cfg.j2
        dest: ../ssh.cfg
    - name: Reload inventory file
      meta: refresh_inventory

- name: Setup docker and docker compose
  hosts: aws
  become: True

  tasks:
    - name: Install EPEL repository on RedHat
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
      when: ansible_distribution == 'RedHat'
    - name: Install EPEL repository on CentOS
      yum:
        name: epel-release
        state: present
      remote_user: centos
      when: ansible_distribution == 'CentOS'
    - name: Install docker and docker compose
      yum:
        name: docker, docker-compose
        state: present
    - name: Enable and start docker service
      service:
        name: docker
        state: started
        enabled: True
...
