---
- name: Set up the bastion host as an ansible controller host
  hosts: all
  become: True

  tasks:
    - name: Install EPEL repository on RedHat
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
      when: ansible_distribution == 'RedHat'
    - name: Install EPEL repository on CentOS
      yum:
        name: epel-release
        state: present
      remote_user: centos
      when: ansible_distribution == 'CentOS'
    - name: Install docker and docker compose
      yum:
        name: docker, docker-compose
        state: present
    - name: Enable and start docker service
      service:
        name: docker
        state: started
        enabled: True
...
